FROM resin/%%RESIN_MACHINE_NAME%%-python

#switch on systemd init system in container
ENV INITSYSTEM on
ENV READTHEDOCS True

COPY . /usr/src/app
WORKDIR /usr/src/app
COPY ./requirements.txt /requirements.txt

RUN sudo apt-get update && sudo apt-get install -y python-picamera python-yaml imagemagick && pip install -r /requirements.txt

CMD ["bash","start.sh"]

